### ISSUE TITLE
a way to let ngsParalog overwrite files?

### ISSUE THREAD

**Issue by TeresaPegan** [tplinderoth/ngsParalog#2]
Hello! I have been using ngsParalog in my work and it's very helpful!
I was wondering, though, if there is a way to allow ngsParalog to overwrite files? I have been using this program in large array jobs, and this means that whenever I need to redo something I end up with hundreds of files that I have to delete before I can run it again. Otherwise ngsParalog just prints a message that the file already exists and exits. 
This is a really useful safety feature in general, but it would be great to be able to turn it off while debugging scripts etc. Let me know if there's a way!
Thanks,
-Teresa

**Comment by tplinderoth** [comment]
Hi Teresa,
Very glad to help out. I totally understand needing to run in many jobs since I haven't multithreaded the program yet (hopefully soon...). I just pushed a changed that allows you to run it with '-allow_overwrite 1'. This should let you overwrite previous outputs. By default, preventing overwriting is still on. I just quickly modified things and haven't tested it yet, so if you have issues with it let me know and I'll address it and ensure it works.

**Comment by TeresaPegan** [comment]
Thanks so much for such a fast response! I will give it a try and let you know.

**Comment by TeresaPegan** [comment]
I updated the repository and I can see that I have the updated version of Argparser.cpp with the  _allow_overwrite(0) line. However, when running the script with '-allow_overwrite 1', I get the message:
"Unknown argument: -allow_overwrite
-->exiting"

**Comment by tplinderoth** [comment]
Sorry Teresa, was in a bit of a rush when I made the previous change and there was a typo, which I've now fixed. I tested it out and it all seems to work on my end. Try pulling again, compile it, and rerun. If you still have any issues let me  know, but I think it should be good (fingers crossed).

**Comment by TeresaPegan** [comment]
Looks like it's working great now! Thanks so much!
